### ISSUE TITLE
Read nii

### ISSUE THREAD

**Issue by cwule** [janus3D/janus3D_toolbox#5]
After successfully loading the obj-file, it took me a while to get back to this but now I am having problems loading nii files. This might actually rather be a problem with the FieldTrip toolbox than janus3D. However, I was wondering, do you have an example dataset (both obj and nii) that I can use to try out the toolbox to see whether it is the fault of my data or of the matlab code?

**Comment by cwule** [comment]
Ok, it was a problem with the field trip toolbox. Need to get the latest version from github instead of installing it via Matlab-Apps.

**Comment by annahensch** [comment]
Hi - I also have a problem loading the .nii file. I am getting these errors after installing the latest version of Fieldtrip from Github (https://github.com/fieldtrip/fieldtrip). The error messages say there are missing symbols, and many more things wrong (Error in ft_read_mri (line 79); Error in janus3D>load_MRI_Callback (line 237); Error in gui_mainfcn (line 95); Error in janus3D (line 20); ...)

**Comment by TommyClausner** [comment]
Could be a problem of Matlab and or Fieldtrip version. I would try MatLab 2015a + the github version of Fieldtrip
